server:
  port: 8390
  servlet:
    context-path: /provide
spring:
  application:
    name: feign-provide-server
eureka:
  hostname: localhost
  port: 8290
  client:
#    register-with-eureka: true
#    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.hostname}:${eureka.port}/eureka/
logging:
  level:
    root: debug